{{ if .Values.faros.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-red.fullname" . }}-faros
  labels:
    {{- include "kube-red.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.faros.token | b64enc }}
{{ end }}
