{{- if .Values.permissions.enabled -}}
{{- if .Values.permissions.clusterAdmin -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: {{ include "kube-red.fullname" . }}
subjects:
 - kind: ServiceAccount
   name: {{ include "kube-red.fullname" . }}
   namespace: {{ .Release.Namespace }}
roleRef:
   kind: ClusterRole
   name: cluster-admin
   apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
