{{- if .Values.permissions.enabled -}}
{{- if .Values.permissions.namespaceAdmin -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "kube-red.fullname" . }}-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: {{ include "kube-red.fullname" . }}
subjects:
 - kind: ServiceAccount
   name: {{ include "kube-red.fullname" . }}
   namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kube-red.fullname" . }}-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
